name: appinio_social_share
description: Supports sharing text, images, files and text with image to social media (Facebook, Instagram, Instagram Story, Messenger, Telegram, WhatsApp, Twitter, SMS, System, etc.).
version: 0.4.1
homepage: https://github.com/riccardo-rusca/flutter_social_share.git
repository: https://github.com/riccardo-rusca/flutter_social_share.git

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appinio.socialshare.appinio_social_share
        pluginClass: AppinioSocialSharePlugin
      ios:
        pluginClass: AppinioSocialSharePlugin
